# Given arguments passed into the program at runtime, determine if the given string should be translated to English or Braille.
# For Braille, each character is stored as a series of O (the letter O) or . (a period).
# Store Braille symbols as a 6 character string reading left to right, line by line, starting at the top left. See examples below.
# When a Braille capital follows symbol is read, assume only the next symbol should be capitalized.
# When a Braille number follows symbol is read, assume all following symbols are numbers until the next space symbol.
b_dict = {
    'a':"o.....",
    'b':"o.o...",
    'c':"oo....",
    'd':"oo.o..",
    'e':"o..o..",
    'f':"ooo...",
    'g':"oooo..",
    'h':".oo...",
    'j':".ooo..",
    'k':"o...o.",
    'l':"o.o.o.",
    'm':"oo..o.",
    'n':"oo.oo.",
    'o':"o..oo.",
    'p':"ooo.o.",
    'q':"ooooo.",
    'r':"o.ooo.",
    's':".oo.o.",
    't':".oooo.",
    'u':"o...oo",
    'v':"o.o.oo",
    'w':".ooo.o",
    'x':"oo..oo",
    'y':"oo.ooo",
    'z':"o..ooo",
    '1':"o.....",
    '2':"o.o...",
    '3':"oo....",
    '4':"oo.o..",
    '5':"o..o..",
    '6':"ooo...",
    '7':"oooo..",
    '8':"o.oo..",
    '9':".oo...",
    '0':".ooo..",
    'cap':".....o",
    'dec':".o...o",
    'num':".o.ooo",
    '.':"..oo.o",
    ',':"..o...",
    '?':"..o.oo",
    '!':'..ooo.',
    ':':"..oo..",
    ';':"..o.o.",
    '-':"....oo",
    '/':".o..o.",
    '<':".oo..o",
    '>':"o..oo.",
    '(':"o.o..o",
    ')':".o.oo.",
    ' ':"......"
}

